Migrate to 0.8.0
gt-ostis-dev/gt-knowledge-base pull request #41
Opened 2023-10-03 14:53 UTC by qaip

2023-11-26 16:06 UTC, MksmOrlov requested changes

2023-11-26 16:06 UTC, MksmOrlov commented on gt-book/exercise/1.1/section_graph_exercise_1_1_1.scs
Почему удаляете это и другие упражнения?

2023-11-26 16:06 UTC, MksmOrlov commented on gt-book/exercise/concept_exercise.scs
> +<- sc_node;
```suggestion
<- sc_node_class;
```
sc_node_not_relation нужно переименовывать в sc_node_class

2023-11-28 06:17 UTC, kilativ-dotcom commented on subject_areas/subject_area_of_connected_graph_structures/relations/nrel/nrel_brother_of_a_vertex.scs
в этом и в нескольких следующих файлах sc_node_not_relation надо поменять на sc_node_norole_relation

2024-09-21 11:24 UTC, merged